-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME, '%H') HOUR, COUNT(*) COUNT FROM ANIMAL_OUTS 
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY DATE_FORMAT(DATETIME, '%H')
ORDER BY DATE_FORMAT(DATETIME, '%H') 
